language: sml

before_install:
  - sudo apt-get install -y mlton gcc-multilib
  - wget https://github.com/melsman/mlkit/archive/v4.3.13.tar.gz
  - tar -xzvf v4.3.13.tar.gz
  - pushd mlkit-4.3.13 && ./autobuild && ./configure --prefix=/usr && make && sudo make install && popd

script:
  - make
  - make test
